### PR TITLE
Update main.nim

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
If you don't plan to inherit from Agent - you don't need methods at all!

**Comment by peheje** [comment]
Hi Daniil. Cool thanks for your interest. I'll pull tomorrow and hopefully
get some parallel speedup going.

**Comment by peheje** [comment]
Hey Daniil
Thanks for the advice it worked great, much cleaner with proc and no {.base.} needed.
I changed it instead of pulling the request because I didn't know how to accept the pull request after changes.

I can see you are a main contributor to Nim, do you mind if I ask you a question? I have appended the question if you feel like it. But if not thanks for the help.

Question on github: https://stackoverflow.com/questions/46900036/nim-parallel-loop-with-mutating-state

**Comment by ghost** [comment]
@peheje parallel would run your code on many cores, so you can't mutate some variable from different threads (well you can, but this will be undefined behaviour).
It's better if you would ask your question on Nim forum

**Comment by peheje** [comment]
Cool. I'll try to ask there.

**Pull request closed without merging**
